### ISSUE TITLE
Content TODO list

### ISSUE THREAD

**Issue by diogotcorreia** [diogotcorreia/resumos-leic#619]
This issue is a continuously updated list of content that is missing or needs to be improved on the site.
Consider this a starting place if you want to contribute!

### Álgebra Linear (AL)

- [ ] All content

### Análise e Modelação de Sistemas (AMS)

- [ ] All content

### Aprendizagem (Apre)

- [ ] All content

### Análise e Síntese de Algoritmos (ASA)

_complete_

### Bases de Dados (BD)

- [ ] All content (@diogotcorreia WIP)

### Cálculo Integral e Diferencial I (CDI-I)

_complete_

### Cálculo Integral e Diferencial II (CDI-II)

- [ ] Check which content might not be relevant anymore due to MEPP

### Cálculo Integral e Diferencial III (CDI-III)

- [ ] Adicionar forma geral da fórmula de variação das constantes (para equações diferenciais com matrizes)
- [ ] Adicionar exemplo de equação redutível a exata
- [ ] Resolver [gralha de `-a(t)` no fator integrante](https://resumos.leic.pt/cdi-iii/equacoes-diferenciais-ordinarias#caso-geral---n%C3%A3o-homog%C3%A9neo)

### Computação Gráfica (CG)

- [ ] All content

### Compiladores (Comp)

- [ ] All content

### Engenharia de Software (ES)

- [ ] All content

### Física I (Fis-I)

- [ ] All content (@diogotcorreia WIP)

### Física II (Fis-II)

- [ ] Missing major cleanup and more detailed explanations

### Fundamentos da Programação (FP)

- [ ] All content

### Gestão (Ges)

- [ ] Missing some small cleanup - some parts are not clearly explained

### Inteligência Artificial (IA)

- [ ] All content

### Introdução à Arquitetura de Computadores (IAC)

 - [ ] All content

### Introdução a Algoritmos e Estruturas de Dados (IAED)

_complete_

### Introdução à Engenharia Informática (IEI)

It's empty but I don't think there's anything to put here

### Interação Pessoa-Máquina (IPM)

- [ ] All content

### Lógica para Programação (LP)

_complete_

### (Elementos da) Matemática Discreta (EMD)

- [ ] Check which content might not be relevant anymore due to MEPP

### Organização de Computadores (OC)

- [ ] All content

### Probabilidade e Estatística (PE)

- [ ] Math content (@Calhau18 WIP)
- [ ] R programming language content

### Programação com Objectos

_complete_

### Redes de Computadores

- [ ] All content

### Sistemas Distribuídos (SD)

- [ ] All content

### Sistemas Operativos (SO)

_complete_

### Teoria da Computação (TC)

- [ ] All content (@Calhau18 WIP)
